name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: 'sapmachine'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
